language: java

jdk:
    - oraclejdk8

services:
    - mysql

env:
    - PROJECT_FOLDER=aplikasi-distribusi-web

before_install: 
    - mysql -uroot -e "grant all on kyurifood.* to kyurifood@localhost identified by 'kyurifood'"
    - mysql -uroot -e "drop database if exists kyurifood"
    - mysql -uroot -e "create database kyurifood"

before_script:
    - cd $PROJECT_FOLDER

after_success:
    - mvn jacoco:report coveralls:report
